ccc-certifier-framework/certifier-framework-for-confidential-computing

- src/sev_policy.json
- utilities/policy_generator.cc
- utilities/policy_generator.mak
- utilities/policy_generator_info.txt
- utilities/policy_schema.json
Added first version of the Certifier policy schema and the generator app stub to validate input policy against the schema. A sample SEV policy with platform properties is also added.
> Started Policy Generator utility development

- src/sev_policy.json
- utilities/policy_generator.cc
- utilities/policy_generator_info.txt
- utilities/policy_schema.json
Added policy file parsing and command generation capabilities to the Policy Generator.
> Completed first version of Policy Generator

- sample_apps/simple_app_under_sev/instructions.txt
- sample_apps/simple_app_under_sev/sev_policy.json
- utilities/policy_generator_info.txt
Added JSON policy to the SEV simple app and updated instructions for policy generator. Also validated the simple app end-to-end on real SEV SNP hardware platform.
> Add JSON policy to SEV Simple App and verify on SEV hardware

- certifier_service/certlib/certlib_proofs.go
- certifier_service/simpleserver.go
Certifier service initial changes
> Skeleton for gramine verification

- src/sev-snp/sev_support.cc
Added optional parameters with default values. Derive sealing keys from VCEK with Measurement and Policy mixed in by default.
> Update SEV-SNP KDF parameters.

- src/sev-snp/attestation.h
- src/sev-snp/sev_report.cc
Updated the Attestation Report Structure to be compliant with newer firmware versions.
Resolves: #33
> snp: Updating Attestation Report

- Doc/developer_tour.md
- application_service/app_service.cc
- include/certifier_framework.h
- sample_apps/analytics_example/enclave/ecalls.cc
- sample_apps/att_systemd_service/attsvc.cc
- src/support.cc
This is a very minor fix to enlarge the maximum possible authenticated encryption key size.
> minor key size fix

- utilities/policy_generator.cc
Fixed policy generator bug when multiple measurements and multiple claims are present.
> Fix Policy Generator bug

- src/support.cc
- src/support_tests.cc
A few more error messages fixes
> Small key improvements

- src/certifier.cc
This commit does minor tweaks to couple of 'error' messages emitted from SEV_SNP-specific VCEK-related code fragments. 
- Deleted one error message, and change another to Info category.
The remaining message will still be raised when running pytests, but it's benign, so should not be troubling to end-users.
> (#180) Rework few error msgs & inclusion of SEV_SNP code in shared libs

- certifier_service/teelib/Makefile
- sample_apps/run_example.sh
- sample_apps/simple_app_under_gramine/gramine_example_app.manifest.template
Fixed some build and test related issues with Gramine/OE. These were only exposed on the SGX testbed.
> Fix build and test script

- sample_apps/multidomain_simple_app/multidomain_client_app.cc
- sample_apps/multidomain_simple_app/multidomain_server_app.cc
- sample_apps/simple_app/example_app.cc
- sample_apps/simple_app_under_app_service/service_example_app.cc
- sample_apps/simple_app_under_gramine/gramine_example_app.cc
- sample_apps/simple_app_under_islet/islet_example_app.cc
- sample_apps/simple_app_under_keystone/keystone_example_app.cc
- sample_apps/simple_app_under_oe/enclave/ecalls.cc
- sample_apps/simple_app_under_oe/host/host.cc
- sample_apps/simple_app_under_sev/sev_example_app.cc
Fix tests so they don't silently fail.
> This change fixes CI tests that silently fail.

- MAINTAINERS.md
- SECURITY.md
Minor cleanup of `SECURITY.md` and updates to email-IDs of maintainers.
> Cleanup and update SECURITY.md contents and maintainer's email IDs.

- CI/scripts/README.md
- tests/README.md
Update `CI/scripts/README.md` to reference test.sh script. Add a new `tests/README.md` documenting how-to use the newly added `test.sh` script.
> Update tests-related README.md files.

- src/certifier_tests.mak
> Use pkg-config for finding Python include dir

- sample_apps/run_example.sh
This commit attempts to improve the behaviour of the rm_non_git_files sub-command of run_example.sh . The objective of this command is to clean-up build-outputs and other [stale] artifacts that may have been produced by a prior execution of this script. We may be, inadvertently, also deleting user's config-/env-files that reside in the project's sub-tree. This commit changes the behaviour of rm_non_git_files to now only delete the files registered in the .gitignore list.
Also, now "--dry-run rm_non_git_files" will only print an info message without actually deleting all affected files.
---
NOTE: @rgerganov - let's discuss this solution.
As mentioned in [this comment](https://github.com/vmware-research/certifier-framework-for-confidential-computing/issues/215#issuecomment-1792701926) for …
> (#215) Prevent rm_non_git_files from rm'ing user's config/env-files

- INSTALL.md
Minor updates to `INSTALL.md` to reflect steps for required s/w packages: `uuid-dev` and `python3-pip`
> (#240) INSTALL.md: Include install of uuid-dev python3-pip

- README.md
[Project OpenSSF Badge Score](https://www.bestpractices.dev/en/projects/8912) Added Project Documentation. 
If you can provide a URL to your tooling, or a brief explanation of why NOT using analysis tools on this project, I will be able to update this score to 100%:
1. At least one **static code analysis tool** (beyond compiler warnings and "safe" language modes) MUST be applied to any proposed major production release of the software before its release, if there is at least one FLOSS tool that implements this criterion in the selected language.
2. It is SUGGESTED that at least one **dynamic analysis tool** be applied to any proposed major production release of the software before its release, but not mandatory.
> OpenSSF Badge Updated

- sev-snp-simulator/sevguest.c
More detailed explanation here: https://sysprog21.github.io/lkmpg/
> Fix compilation error related to Linux kernel version change

- sample_apps/run_example.sh
> Fixed run_cmd trap

- .github/workflows/build.yml
- CI/scripts/cppcheck.sh
- CI/scripts/test.sh
- acl_lib/acl_lib.mak
- acl_lib/test_acl.cc
- sample_apps/cleanup.sh
- src/keystone/shim_test.mak
> Further tests 1

- sample_apps/simple_app/example_app.mak
- sample_apps/simple_app/instructions.md
- sample_apps/simple_app/prepare-test.sh
- sample_apps/simple_app/run-test.sh
- vm_model_tools/examples/scenario1/instructions.md
> Simple app sh

- sample_apps/multidomain_simple_app/multidomain_app.mak
- sample_apps/multidomain_simple_app/multidomain_client_app.cc
- sample_apps/multidomain_simple_app/prepare-test.sh
- sample_apps/multidomain_simple_app/run-test.sh
- sample_apps/multidomain_simple_app/sample_run.txt
Some prep files for multidomain port to new API.
> Multidomain prep 1

- sample_apps/simple_app_under_sev/instructions.md
- sample_apps/simple_app_under_sev/prepare-test.sh
- sample_apps/simple_app_under_sev/run-test.sh
- sample_apps/simple_app_under_sev/sev-client-call.sh
- sample_apps/simple_app_under_sev/sev_example_app.mak
> start of sev port to new API

- application_service/app_service.cc
- application_service/app_service.mak
- application_service/instructions.md
- application_service/prepare-test.sh
- application_service/run-test.sh
- sample_apps/simple_app_under_sev/sev-client-call.sh
> Application server scripts work

- application_service/app_service.cc
- application_service/app_service.mak
- application_service/prepare-test.sh
- application_service/run-test.sh
- sample_apps/simple_app_under_app_service/prepare-test.sh
- sample_apps/simple_app_under_app_service/run-test.sh
- vm_model_tools/examples/scenario1/prepare-test.sh
- vm_model_tools/examples/scenario1/run-test.sh
> App service new api draft 3

- application_service/prepare-test.sh
- sample_apps/simple_app/prepare-test.sh
- sample_apps/simple_app_under_app_service/prepare-test.sh
- sample_apps/simple_app_under_app_service/service_example_app.cc
- vm_model_tools/examples/scenario1/prepare-test.sh
> more scripts fixed

- CI/scripts/test.sh
- acl_lib/test_data/file_2
- src/cc_helpers.cc
> fixed acl test

- CI/scripts/test.sh
- acl_lib/test_data/file_2
- src/cc_helpers.cc
- src/certifier.cc
- vm_model_tools/examples/scenario1/test_script.sh
- vm_model_tools/src/cf_key_client.cc
- vm_model_tools/src/cf_key_server.cc
- vm_model_tools/src/cf_support.cc
- vm_model_tools/src/cf_support.h
- vm_model_tools/src/cf_support_test.cc
- vm_model_tools/src/cf_utility.cc
- vm_model_tools/src/cf_utility.mak
- vm_model_tools/src/cryptstore.proto
> Key servers 1

- vm_model_tools/examples/scenario1/test_script.sh
> Fixed script

- vm_model_tools/src/cf_support.cc
> Key servers 2
