ccc-certifier-framework/certifier-framework-for-confidential-computing

src/cc_helpers.cc
src/simulated_enclave.cc
src/support.cc
src/test_channel.cc
src/test_support.cc

The file_size() function should return negative values when the specified file is missing.

Fix the file_size() return value

---

src/cc_helpers.cc

cc_helpers.cc doesn't contain tests and shouldn't include gtest.h. This patch allows building the Certifier in contstrained environments (like enclaves) where gtest is not available.

Remove unused include in cc_helpers.cc

---

certifier_service/go.mod
certifier_service/go.sum

The certifier service cannot be built unless GO111MODULE=off is set. This patch fixes this by adding go.mod and go.sum files.

Add go.mod and go.sum for the certifier service

---

src/cc_helpers.cc

SSL_connect returns 1 on sucess and <= 0 on failure. If the peer ceritifate is missing or invalid, SSL_connect returns -1.

Fix checking the return value of SSL_connect()

---

application_service/instructions.txt
application_service/script
certifier_service/simpleserver.go
sample_apps/analytics_example/README.md
sample_apps/asylo_secure_grpc/README.md
sample_apps/asylo_secure_grpc/script
sample_apps/simple_app/instructions.txt
sample_apps/simple_app/script
sample_apps/simple_app_under_app_service/instructions.txt
sample_apps/simple_app_under_app_service/script
sample_apps/simple_app_under_sev/instructions.txt
sample_apps/simple_app_under_sev/script

The 'path' parameter is not used and should be removed.

Remove 'path' parameter of simpleserver

---

CONTRIBUTING.md

Fixed 2 links in the "formatting commit messages" section that were broken due to incorrect markdown formatting.

Fixed links in CONTRIBUTING.md

---

CONTRIBUTOR_LADDER.md
GOVERNANCE.md

Adding draft governance and contributor ladder documentation after discussing the need to have these docs in a meeting with @jlmucb.
I suspect that we will need to iterate on this PR, since I guessed at a few things and made arbitrary choices :) 
None of this is decided at this point, and we can change things as much as we need to, so please review and provide feedback so that we can improve on these docs and make sure that they meet your needs for the project.

DRAFT: Governance Documentation

---

certifier_service/certlib/certlib_proofs.go
certifier_service/oelib/oeverify.c
certifier_service/oelib/oeverify.h
certifier_service/oelib/oeverify_dummy.c
certifier_service/oeverify/oeverify.go
sample_apps/simple_app_under_oe/README.md
sample_apps/simple_app_under_oe/enclave/ecalls.cc
sample_apps/simple_app_under_oe/enclave/enc.conf
sample_apps/simple_app_under_oe/instructions.txt
sample_apps/simple_app_under_oe/script
src/cc_helpers.cc
src/certifier.cc
src/openenclave/attestation.cc
src/openenclave/oe_support.cc
src/openenclave/sealing.cc

Contains two patches. The first is a fix that ignores the VSE plaftorm certificate. This one is generic. The second patch updates the proof and evidence for OE so that we can have a policy without VSE cert (endorsement).

OE SGX Real Hardware Updates

---

.gitignore
application_service/app_service.mak
openenclave_test/enclave/oe_certifier.mak
sample_apps/analytics_example/enclave/oe_certifier.mak
sample_apps/simple_app/example_app.mak
sample_apps/simple_app_under_app_service/service_example_app.mak
sample_apps/simple_app_under_sev/sev_example_app.mak
sample_apps/simple_app_under_sev/sev_example_app_with_dummy.mak
src/certifier.mak
src/certifier_tests.mak
utilities/cert_utility.mak
utilities/policy_generator.mak
utilities/policy_utilities.mak

Fix diff Makefile's 'clean' recipe to use "rm -rf" on *.o's so that we don't get noisy messages reporting that *.o is not found. These occur when someone attempts 'clean' on a new branch, before making any executables.
Add more patterns to .gitignore rules.
----
**NOTE**: To reviewers: This change-set is mostly a cleanup-type changes to reduce noisy messages when running `clean` in a new code branch. I ran into these while going thru diff steps / instructions for sample programs.
As part of the build(s), we seem to produce many artifacts in the code line itself. So this commit enhances existing rules in `.gitignore` to exclude some of the generated files. 
Please see my annotations to `.gitignore` before we finalize this change. We don't want to accidentally ignore a file that should be …

Fix 'clean' recipe  to avoid getting noisy messasges. Update .gitignore rules

---

sample_apps/simple_app/instructions.md

Rewrite sample_apps/simple_app/instructions.txt instructions in md-file format, in new file instructions.md .
---
NOTE: To the reviewer. 
The final form of simple_app/instructions.md can be found in my [dev-branch, here](https://github.com/vmware-research/certifier-framework-for-confidential-computing/blob/agurajada/simple_app-Instr.md/sample_apps/simple_app/instructions.md).
The contents are identical to current version of instructions.txt but just re-formatted to use md-style formatting. The new style is more readable and the commands to be issued stand-out on their own.
If this new md-format is acceptable, I will delete instructions.txt as part of this change-set.
Over time, the instructions.txt in other sample programs can also be converted to the new style as I go through each sample …

Rewrite instructions.txt in md-file formatting.

---

include/cc_helpers.h
sample_apps/simple_app/example_app.cc
sample_apps/simple_app/example_app.mak
src/cc_helpers.cc
src/support.cc
utilities/cert_utility.mak
utilities/policy_generator.mak
utilities/policy_utilities.mak

This commit tightens some error-handling and reporting failures in helper methods. These were discovered while trying to setup simple_app in a new env.
- server_dispatch() now returns 'bool'. Couple of usages in the code-flow of simple_app are updated to deal with this failure.
- Cleaned-up and improved some status / progress printf() messages
- Replaced, in some places, inline name of function with __func__.
-  Additionally, some warnings in support.cc are fixed. To improve overall code quality, I am introducing "-Werror" in all Makefiles. This way, in future, if compiler warnings creep-in, that will cause build failures. This will force us to keep the code free of warnings, too.
----
**NOTE: To reviewer(s)**: 
While setting up `sample_app/simple_app` in my Nimbus-VM environment, I ran …

Improve error handling and return of failure $rc for simple_app

---

include/cc_helpers.h
include/certifier.h
sample_apps/att_systemd_service/attsvc.cc
sample_apps/simple_app/example_app.cc
sample_apps/simple_app_under_app_service/service_example_app.cc
sample_apps/simple_app_under_sev/sev_example_app.cc
src/cc_helpers.cc
src/support.cc
utilities/appoint_platform.cc
utilities/cert_utility.cc
utilities/combine_properties.cc
utilities/embed_policy_key.cc
utilities/key_utility.cc
utilities/make_environment.cc
utilities/make_indirect_vse_clause.cc
utilities/make_platform.cc
utilities/make_property.cc
utilities/make_signed_claim_from_vse_clause.cc
utilities/make_simple_vse_clause.cc
utilities/make_unary_vse_clause.cc
utilities/measurement_init.cc
utilities/measurement_utility.cc
utilities/package_claims.cc
utilities/policy_generator.cc
utilities/print_packaged_claims.cc
utilities/print_signed_claim.cc
utilities/print_vse_clause.cc
utilities/sample_sev_key_generation.cc
utilities/simulated_sev_attest.cc
utilities/simulated_sev_key_generation.cc

This commit relocates the Copyright notice to be at the top of the file so it's consistently placed at the very top in all files. In a few files, user #include's are re-arranged so that they follow system .h #includes. 
There are no other code-/logic-changes with this commit.
----
**NOTE: To reviewers**: This change-set is mostly of a cleanup-nature. However, lots of source files are affected.
In principle, by simply rearranging some user-#include's to appear -after- system #include's `.h` files should not regress compilation. We don't quite have a full build-and-test CI. So, what's the way to ensure that these source file edits do not regress compilation? 
I have left this PR in 'draft' - stage just so that we can talk about this change, and to figure out how to test these diffs to …

Relocate copyright notice to be at top of the file. Other minor edits.

---

.github/workflows/build.yml
application_service/app_service.mak
certifier_service/certlib/certlib_proofs.go
include/cc_useful.h
sample_apps/simple_app/example_app.mak
sample_apps/simple_app_under_app_service/service_example_app.mak
sample_apps/simple_app_under_gramine/gramine_example_app.mak
sample_apps/simple_app_under_sev/sev_example_app.mak
sample_apps/simple_app_under_sev/sev_example_app_with_dummy.mak
src/cc_helpers.cc
src/cc_useful.cc
src/certifier.mak
src/certifier_tests.mak

This commit refactors a bit of existing inline code that maps SSL error-code IDs to human-readable string describing the error.
- Introduce cc_useful.h / cc_useful.cc to define a new optlookup{} struct. Add optbyid(), to lookup string associated with an ID
- Add Ssl_errors[] optlookup array.
- Replace inline body of print_ssl_error() with call to optbyid() to lookup error-ID to error-description (strng).
- Use ssl_strerror() to print client-side SSL-errors.
This debug infra has been exercised while setting up simple_app on Nimbus-VM, where we are [strangely] encountering SSL errors.
- Delete couple of imports in certlib/certlib_proofs.go that result in Go compilation warnings.
-----
**NOTE to the reviewer**: 
This tracing / debugging refactoring came about while I was stabilizing the …

Add Ssl_errors[] as an optlookup{} table to map SSL-error IDs to messages.

---

utilities/appoint_platform.cc
utilities/cert_utility.cc
utilities/combine_properties.cc
utilities/embed_policy_key.cc
utilities/key_utility.cc
utilities/make_environment.cc
utilities/make_indirect_vse_clause.cc
utilities/make_platform.cc
utilities/make_property.cc

Enhance few programs in utilities/ sub-dir to call gflags::SetUsageMessage(), so that basic description of the program can be seen via --help output. Add, where needed, usage_str(), to report basic usage information.
------
**NOTE: To reviewer(s)**: 
This is just a sample set of changes to add improved help / usage messages to a small collection of programs. I think, by consistently reporting a small one-liner explaining what the purpose of each program is, we can improve the on-boarding experience for new users.
The actual content of the message will need to be hand-crafted for each program. I do not have sufficient familiarity with each program to craft a message. So, the bulk / brunt of the review process will be for the code-author and me to sit down and hash-out a descriptive message …

Add SetUsageMessage() and usage_str to set of programs in utilities/

---

.github/workflows/build.yml
sample_apps/simple_app/cleanup.sh
sample_apps/simple_app/run_example.md
sample_apps/simple_app/run_example.sh

This commit introduces `run_example.sh` as a single wrapper script to package the multiple steps, from `instructions.txt`, to build and setup the simple_app example program. 
The objective of this kind of packaging is to simplify the on-boarding for new users who wish to experiment with the Certifier Library and our example programs.
Usage: `run_example.sh [--help | --list]`
By default, with no arguments, the script will run through all the steps to compile, build and setup the app-as-server, app-as-client invocation  to demo that the Certifier library is basically working.
--help will give help / usage info.
--list will display the functions implementing each step.
Normal invocation can be as simple as: ` $ run_example.sh`
User can break this up into a 2-step process, executing the 2nd …

Add run_example.sh for simple_app/, as a single script to run the entire setup

---

.github/workflows/build.yml
sample_apps/simple_app/README.md
sample_apps/simple_app/cleanup.sh
sample_apps/simple_app/run_example.sh
utilities/policy_utilities.mak

Remove dependency of simple_app/run_example.sh on existence of src/certifier.pb.cc
This commit cleanses some logic in simple_app/run_example.sh to clean-up all non-git-tracked artifacts (.o's, .exe's, .cc/.h files etc.) from the dev area where steps to build-and-run simple_app are executed.
Previously, (in CI), other steps would have run 'make -f certifier.mak' in src/ sub-dir, that produces the required src/certifier.pb.cc file.
Rework the rules in utilities/policy_utilities.mak to correctly compile the protobuf file (from src/) to generate *.pb.cc/*.pb.h in the required sub-dirs.
Fix shellcheck errors in shell script.

Add rm_non_git_files() that only does 'git ls-files' for now.

---

src/certifier.cc
src/support.cc

This small change lets us specify the authenticated encryption algorithm for Protect_Blob.  The default is "aes-256-cbc-hmac-sha256" but you can also specify "aes-256-gcm"."  This  keeps us in conformance with CNSA 2.0.

Allow specification of authenticated encryption algorithm for Protect

---

sample_apps/cleanup.sh
sample_apps/run_example.sh

This commit pre-stages the location of two scripts that were developed for setting up and running the simple_app/ . The idea is to parametrize run_example.sh so that it can be used to build-and-test more than a few sample apps, starting from simple_app/. This extension will be done in follow-on PRs.

Move run_example.sh & cleanup.sh from simple_app/ to sample_apps/

---

utilities/cert_utility.mak
utilities/policy_utilities.mak

Previous commit (@ SHA c7963d9) added -Werror to several Makefiles. This causes builds of utility programs to fail on SGX platforms while compiling protobuf-generated files. This commit resolves those failures by relaxing this flag specifically while compiling these generated files. One other fix is needed to pick-up right version of OpenSSL libs while building policy-utilities exes.
With these fixes, the following should work cleanly on SGX platform:
$ make -f cert_utility.mak clean
$ LOCAL_LIB=/usr/local/lib64 make -f cert_utility.mak $ LOCAL_LIB=/usr/local/lib64 make -f policy_utilities.mak
----
**NOTE**: To reviewer(s). These build failures have been fixed in my current dev-branch (under upcoming fixes for issue #67).
I am peeling those off that in-flight work to push separately to …

(#58) Fix build failures for utilities on SGX platform.

---

src/certifier.proto
src/support.cc

There are usecases when we need to export the RSA private key from the policy store. One example is running an HTTPS endpoint with the certificate obtained from the Certifier service. In such cases we need to save all key properties (n, e, d, p, q, dmp1, dmq1, iqmp) in order to reconstruct the key outside of the policy store.

Export all RSA key properties

---

certifier_service/certlib/certlib_support.go
certifier_service/simpleserver.go

This allows running HTTPS endpoints with the admission certificate

Add the IP address of the remote peer in the admission certificate

---

.github/workflows/build.yml
sample_apps/run_example.sh

This commit adds `--dry-run` argument to `run_example.sh`. This will allow us to test changes to Bash script logic for all sample programs, fairly painlessly, without having to actually re-run this script for each supported sample program.

Add --dry-run mode to run_example.sh, to exercise script for dev-testing.

---

sample_apps/run_example.sh

This commit simplifies the calling sequence of app-specific step- functions in run_example.sh to use variable name, $SampleAppName, whenever possible. This enforces a naming consistency requirement that step-functions are named, e.g., setup_simple_app() and setup_simple_app_under_oe() etc. This change makes it easier to integrate support for other sample apps under this bash script.
-----
NOTE to the reviewer: This refactoring is essentially no-code-change change set. As long as CI runs and the newly added test cases to exercise `--dry-run simple_app_under_oe` succeed, I am comfortable that these script changes should work cleanly on SGX platform for OE-apps, too.

(#73) run_example.sh: Rework sub-step fns using $SampleAppName variable

---

sample_apps/run_example.sh

This commit simply fixes up all tabs to consistently be 4-chars, and shiftwidth=4. No logic change in script.

Edit run_example.sh to consistently use 4-char tabstop.

---

src/support.cc

As reported in issue #72, couple of files are failing to compile on macOSX. This commit fixes those failures by using long long print specifier, `PRIu64`.
Things seem to work fine on macOSX for `$ make -f cert_utility.mak`.

(#72) Fix print fmt-specifier that causes cc failure on macOSX

---

sample_apps/run_example.sh
sample_apps/simple_app_under_oe/instructions.md

Add build_policy_generator_OE() in the series of steps needed to get setup-with-automated policy generation part of the workflow to run successfully. With this fix, the following should work:
$ run_example.sh simple_app_under_oe setup_with_auto_policy_generation_for_OE 
$ run_example.sh simple_app_under_oe run_test
Update instructions.md to reflect the addition of this small sub-step to the workflow.
----
NOTE: To the reviewer: This usage does not have CI coverage. I hand-tested this manually on sgx machine, and now `run_test` succeeds cleanly as follows:
```
run_example.sh: Running run_simple_app_under_oe_as_client_make_trusted_request
+ set +x
+ ./host/host enclave/enclave.signed run-app-as-client /home/sgx/agurajada/certifier-framework-for-confidential-computing/sample_apps/simple_app_u …
```

Fix run_example.sh to get setup_with_auto_policy_generation_for_OE to work.

---

INSTALL.md
sample_apps/simple_app_under_sev/instructions.txt
sample_apps/simple_app_under_sev/script
sample_apps/simple_app_under_sev/sev_example_app.mak
sample_apps/simple_app_under_sev/sev_example_app_with_dummy.mak
sev-snp-simulator/Makefile
sev-snp-simulator/instructions.txt
sev-snp-simulator/test/Makefile
sev-snp-simulator/test/sev-test.c
src/certifier.mak
src/sev-snp/sev_support.cc
utilities/cert_utility.mak
utilities/policy_utilities.mak

Updated the SEV-SNP simulator to generate keys in fixed system directory so the instructions can be more consistent. Also added some missing compiler flags to remove Protobuf compilation warning.

Update SEV-SNP simulator support

---

src/cca/islet_test/Makefile
src/cca/islet_test/README.md
src/cca/islet_test/attest_seal_test.cc
third_party/islet/include/islet.h
third_party/islet/setup.sh

First, I am glad to collaborate with `Certifier` :)
This PR imports `ISLET SDK` and adds the sample application.
This version runs on x86_64 to integrate easily.
My plan is like:
1. Import ISLET SDK and make the sample app (simulated version on x86_64) << **This PR**
2. Integrate interfaces between `ceritifer` and `islet` (x86_64) << *I hope that certifier developer could help this!*
3. Run sample app on Arm CCA simulator (arm64)
It is for applications running on Arm CCA. ISLET SDK is written in `rust` but we also support `C/C++`.
We use `cbindgen` which is the powerful tool to create headers for rust libraries which expose public C/C++ APIs.
_So please do not modify header directly._
Please refer [this](https://github.com/Samsung/islet/tree/main/sdk) for details.
```
+--------+ …
```

Import ISLET project for Arm CCA

---

.github/workflows/build.yml
sample_apps/run_example.sh
sample_apps/simple_app_under_keystone/temporary_instructions.txt
src/keystone/keystone_shim.cc
src/keystone/keystone_test.cc
src/keystone/shim_test.mak

This commit enhances run_example.sh to 'setup' and 'run_test' the `simple_app_under_keystone`, which has been developed using Keystone shim APIs. Much of the workflow remains unchanged, except the
following salient changes were necessary to get things to work:
- keystone_shim.cc: Rename hard-coded 'keystone_example_app.measurement'
to 'example_app.measurement' . This makes it easy to integrate
workflow with driver shell script as all other sample programs
are using the new name.
- Add setup_emulated_keystone_shim_bins(), to generated the
emulated_keystone_key.bin & emulated_keystone_key_cert.bin
files as a pre-setup work for this app.
- Adjust the script to deal with keystone_example_app.exe program
name.
- Use emulated_keystone_key_cert.bin to construct policy.
- Rearrange sequencing of …

(#106) Integrate build-and-test of Keystone app under run_example.sh

---

src/cca/islet_test/Makefile
third_party/islet/setup.sh

Fixed CCA setup script to add cargo installation to PATH. Also fixed the shim_test build for CCA to look for the correct libislet_sdk.so.

Fix CCA setup and shim test build

---

src/cc_helpers.cc
utilities/embed_policy_key.cc
utilities/print_packaged_claims.cc
utilities/print_signed_claim.cc

This commit tightens some error checking of invalid arguments to few utility programs that were silently failing without reporting error messages.
No new error checks are added; only error messages are being printed when needed.

(#111) Fix checks to report error messages when input args are invalid.

---

certifier_service/certlib/cert1_test.go
certifier_service/certlib/certlib_proofs.go
certifier_service/certlib/certlib_support.go
certifier_service/go.mod
certifier_service/simpleserver.go
certifier_service/test_sized_client.go
certifier_service/test_sized_server.go
deprecated/simpleclient.go.old

This commit mildly reworks Go-package module dir-path names to remove name sub-strings that were added to track dev-history.  `go.mod` name is now the following, to be consistent with naming convention to allow `go get` to work with Git to download the module:
"github.com/vmware-research/certifier-framework-for-confidential-computing/certifier_service"
is being used for go.mod .
All CI-tests seem to run clean with this name change, so it's expected that the Certifier Service build-processes should work correctly on all other platforms, such as Gramine, OE or SEV-enabled hardware.

(#117) Remove private 'v2' refs from Go-module root-dir path

---

.github/workflows/build.yml
CI/scripts/check-gofmt.sh
certifier_service/certlib/cert1_test.go
certifier_service/certlib/certlib_proofs.go
certifier_service/certlib/certlib_support.go
certifier_service/gramineverify/gramineverify.go
certifier_service/isletverify/isletverify.go
certifier_service/oeverify/oeverify.go
certifier_service/simpleserver.go
certifier_service/test_sized_client.go
certifier_service/test_sized_server.go
third_party/asylo/asylo/grpc/auth/core/testdata/generate_test_vectors_test.go

This commit does a one-time apply of default 'gofmt' formatting to all `.go` files in the Certifier repo.
To prevent future divergence, a new `CI/scripts/check-gofmt.sh` script is added, which gets invoked in early steps of `build.yml` . CI-builds will fail if any gofmt violations are seen.
---
**NOTE: To the reviewers**:
Some of the default `gofmt` rules takes out spaces. I think the old code is more readable ... but we'll have to just live with this no-space formatting for now.
I did investigate ways to profile gofmt-formatting, but didn't find anything very customizable.
I think in the longer-term we will need a way to specify format-rules, to make the code a bit more readable per out local styles.

(#120) Apply default 'gofmt' formatting for all .go files in repo.

---

.github/workflows/build.yml
application_service/app_service.mak
certifier_service/isletlib/Makefile
sample_apps/analytics_example/enclave/oe_certifier.mak
sample_apps/run_example.sh
sample_apps/simple_app/example_app.mak
sample_apps/simple_app_under_islet/islet_example_app.mak
sample_apps/simple_app_under_keystone/keystone_example_app.mak
sample_apps/simple_app_under_sev/sev_example_app.mak
src/certifier.mak
src/certifier_tests.mak
src/keystone/shim_test.mak
utilities/cert_utility.mak
utilities/policy_utilities.mak

This commit cleans-up several Makefiles to now support use of parallel make with -j <threads> . The main bug was in the definition of the dependency between:
```
certifier.pb.h: certifier.pb.cc
certifier.pb.cc: certifier.proto
```
The former was missing in some mak-files or was mis-defined along with the latter. Both caused parallel make to often fail.
This commit fixes this for all (commonly-used) *.mak files.
Additionally, run_example.sh is enhanced to supply -j flag, for # of CPUs on the machine.
On CI-Build machines with 2 CPUs, the e2e run-time of all tests drops from ~29+ mins to about ~20 mins with this parallel make support.
---
NOTE: To the reviewer: In multiple CI-build test runs I saw e2e run-times ranging from 16 mins to ~22 mins with this fix. Without parallel make, run-times …

(#147) Fix various Makefiles to support parallel make using -j threads.

---

application_service/app_service.mak
openenclave_test/enclave/oe_certifier.mak
sample_apps/analytics_example/enclave/oe_certifier.mak
sample_apps/simple_app/example_app.mak
sample_apps/simple_app_under_app_service/example_app.mak
sample_apps/simple_app_under_islet/islet_example_app.mak
sample_apps/simple_app_under_keystone/keystone_example_app.mak
sample_apps/simple_app_under_sev/sev_example_app.mak
src/certifier.mak
src/certifier_tests.mak
src/gramine/gramine_tests/gramine_tests.mak
src/keystone/keystone_tests/keystone_tests.mak
src/keystone/shim_test.mak
utilities/cert_utility.mak
utilities/policy_generator.mak
utilities/policy_utilities.mak

This commit refactors existing Makefile-rules to replace hard-coded
file-names (e.g. "certifier_proofs.cc") to instead use Make-provided
automatic variables (such as `$@` and `$<`).
In a few places, use:
- `$(<D)` to name the directory of the 1st pre-requisite
- `$(@D)` to name the directory of the target.
With this change, much of the rules become more compact and follow
a pattern consistent with Make-suggested usage of variables.
Refactor few mak-files to define common_objs list; remove redundant definitions of CFLAGS and other unused symbols / make-rules.
-----
NOTE: To reviewer: This change-set is built on top of PR #148 so that I could use the `-j n` feature to speed up dev-cycles while editing and testing Makefile-diffs. Ignore the diffs from the 1st commit. I have marked-up imp …

(#146) Rework Makefile-rules to use auto-variables $@, $< more widely

---

certifier_service/certprotos/certifier.proto
include/application_enclave.h
include/simulated_enclave.h
include/support.h
src/application_enclave.cc
src/certificate_tests.cc
src/certifier_proofs.cc
src/certifier_tests.cc
src/claims_tests.cc
src/pipe_read_test.cc
src/primitive_tests.cc
src/sev_tests.cc
src/simulated_enclave.cc
src/store_tests.cc
src/support_tests.cc
src/test_channel.cc
src/test_support.cc
src/x509_tests.cc

This commit fixes many `.h` and `.cc` files to relocate the Copyright notice to the top-of-the file. 
No further code / logic changes are included.

Relocate Copyright notice to top-of-file in many .h/.cc files.

---

certifier_service/certlib/certlib_proofs.go
certifier_service/certlib/certlib_support.go
certifier_service/certprotos/certifier.proto
src/certifier.cc

This patch added AMD SEV-SNP VCEK certificate custom extension parsing support. The platform TCB version is now checked as part of the SEV-SNP attestation report verification in addition to signature verification.

Add AMD SEV-SNP VCEK extensions parsing and checks.

---

certifier_service/certlib/certlib_proofs.go
include/certifier_utilities.h
src/certifier.cc
src/sev-snp/sev_vcek_ext.h
src/support.cc
utilities/simulated_sev_key_generation.cc

Added custom extensions with fixed values to the simulator VCEK certificates we generate. The VCEK certificate extension verification check is also removed so we always check for the extensions during report verification.

Add custom extensions to simulator VCEK certificate.

---

include/certifier_framework.h
src/cc_helpers.cc
tests/pytests/test_cert_framework_basic.py

Default constructor for cc_trust_data() ran into seg-faults due to use of uninitialized variables. Refactor the constructor to add  a common private `cc_trust_data_default_init()` method, shared by both constructors. 
Add Python tests which trigger this bug and test the fix.
Good catch!
The only concern I have is that the destructor does not delete the certifiers structures that were newed when adding.
You are correct that the code that does that, below, should be in the destructor (Man, that was a wierd mistake).
for (int i = 0; i < num_certified_domains_; i++) {
if (certified_domains_[i] != nullptr) {
delete certified_domains_[i];
certified_domains_[i] = nullptr;
}
}
delete certified_domains_;
certified_domains_ = nullptr;
num_certified_domains_ = 0;

(#170) Refactor cc_trust_data() constructor to fix bug.

---

sample_apps/analytics_example/README.md
sample_apps/analytics_example/host/host.cc
sample_apps/multidomain_simple_app/instructions.md
sample_apps/multidomain_simple_app/multidomain_client_app.cc
sample_apps/multidomain_simple_app/multidomain_server_app.cc
sample_apps/multidomain_simple_app/script
sample_apps/run_example.sh
sample_apps/simple_app/example_app.cc
sample_apps/simple_app/example_key_rotation.cc
sample_apps/simple_app/instructions.md
sample_apps/simple_app/script
sample_apps/simple_app_under_app_service/instructions.md
sample_apps/simple_app_under_app_service/script
sample_apps/simple_app_under_app_service/service_example_app.cc
sample_apps/simple_app_under_gramine/gramine_example_app.cc
sample_apps/simple_app_under_gramine/instructions.md
sample_apps/simple_app_under_gramine/script
sample_apps/simple_app_under_islet/instructions.md
sample_apps/simple_app_under_islet/islet_example_app.cc
sample_apps/simple_app_under_islet/script
sample_apps/simple_app_under_keystone/keystone_example_app.cc
sample_apps/simple_app_under_keystone/script
sample_apps/simple_app_under_oe/host/host.cc
sample_apps/simple_app_under_oe/instructions.md
sample_apps/simple_app_under_oe/script
sample_apps/simple_app_under_sev/instructions.md
sample_apps/simple_app_under_sev/script
sample_apps/simple_app_under_sev/sev_example_app.cc

This commit does a couple of minor clean-ups of sample-app command interfaces:
- Op 'get-certifier' is renamed to 'get-certified', to be consistent with what's actually going on.
- Op 'warm-restart' is never ever invoked as an external command. Instead, cc_trust_data()->warm_restart() is invoked as part of other ops. Hence, this tag is being removed from the external interface of most sample apps.
Updated docs and work-instructions appropriately.

(#173) Purge warm-restart as sample-app op. Rename op to 'get-certified'.

---

.github/workflows/build.yml
INSTALL.md
certifier_service/certlib/cert1_test.go
certifier_service/certlib/certlib_primitives.go
certifier_service/teelib/Makefile
certifier_service/teelib/tee_primitives.cc
certifier_service/teelib/tee_primitives.h
sample_apps/multidomain_simple_app/instructions.md
sample_apps/multidomain_simple_app/script
sample_apps/run_example.sh
sample_apps/simple_app/instructions.md
sample_apps/simple_app/script
sample_apps/simple_app_under_app_service/instructions.md
sample_apps/simple_app_under_gramine/instructions.md
sample_apps/simple_app_under_gramine/script
sample_apps/simple_app_under_islet/instructions.md
sample_apps/simple_app_under_islet/script
sample_apps/simple_app_under_keystone/script
sample_apps/simple_app_under_oe/instructions.md
sample_apps/simple_app_under_sev/instructions.md

This patch added Go wrappers for the Certifier TEE primitives. These include Attest/Seal/Unseal. We need these APIs to add support for running the Certifier service inside a TEE (e.g., SEV-SNP VM).

Add Go wrappers for Certifier TEE primitives

---

application_service/app_service.mak
certifier_service/teelib/Makefile
sample_apps/simple_app_under_sev/sev_example_app.mak
src/cc_helpers.cc
src/certifier.cc
src/certifier.mak
src/certifier_tests.mak
src/sev-snp/sev_cert_table.cc
src/sev-snp/sev_cert_table.h
src/sev-snp/sev_support.cc
src/sev-snp/sev_support.h

Added support for SEV-SNP extended guest request to fetch platform certificates configured by the host. On platforms where this is supported, we do not need to supply additional parameters during enclave initialization.

Add SEV-SNP extended guest request for platform certificates

---

sample_apps/simple_app_under_gramine_sev/instructions.md
sample_apps/simple_app_under_gramine_sev/policy.json

Added instructions and template policies for building and running simple applications between AMD-SEV and Gramine SGX platforms.

Add instructions for simple application between different platforms

---

src/gramine/gramine_api.h
src/gramine/gramine_api_impl.cc

This patch added SGX platform attributes parsing from SGX quotes. A selected subset is extracted and will be used by the certifier service in the future for SGX platform verification.
(Not an official pull request. Demonstration of attributes extraction.)

Add SGX platform attributes parsing

---

src/gramine/gramine_api_impl.cc

This patch removed the debug code which tests the extraction of SGX attributes from the SGX quote.

Remove debug code to test SGX attributes extraction

---

certifier_service/certlib/certlib_proofs.go
certifier_service/simpleserver.go

This patch added a Go utility that parses the Gramine SGX quote and extracts a subset of platform attributes.

Add Go utilities to parse SGX quote for platform properties

---

certifier_service/certprotos/certifier.proto
include/cc_helpers.h
include/certifier_framework.h
src/Noteontests.md
src/cc_helpers.cc
src/test_channel.cc
utilities/generate_cert_chain.cc
utilities/generate_cert_chain.mak

This checkin implements a request from data village to have different roots for client and server elements in secure_authenticated_channel.
There is also a new utility to generate test cases

Full authentication channel

---

.github/workflows/build.yml
CI/scripts/test.sh

This commit introduces test.sh, refactoring chunks of test
execution code into functions from build.yml into this script.
Full test coverage is retained with this refactoring.
Usage: ./CI/scripts/test.sh --help
Usage: test.sh [--help | --list] [test_all]
The standalone test.sh can now be used in dev-build
environments to run one or all of the test cases.
--list will list the test cases that can be run.
E.g. ./test.sh test-run_example-simple_app will run
the test-chunk named test-run_example-simple_app.

(#184) Refactor build.yml test execution into test.sh functions

---

CI/scripts/test.sh
include/certifier_framework.h
sample_apps/run_example.sh
sample_apps/simple_app_python/example_app.py
src/cc_helpers.cc
tests/pytests/test_certifier_framework.py

This commit completes the remaining work to setup a secure communication
channel between client and server portions of simple_app_python.
This is modelled on the lines of mTLS communication test.
As Python SSL interfaces only deal with certificates / keys from files, we do the following in this work:
- Add external interface to cc_trust_manager{} to write out the private key to a file.
- As part of 'get-certified' operation, the certificate and  private-key for the client & server get written out to files
in their respective application data-dir. The CA-root policy cert will also get written out.
- Introduce server_dispatch() and client_dispatch() methods, to   run under the "app-as-server" and "app-as-client" targets.  These methods will establish the secure SSL channel communication, …

simple_app_python: Complete client-server secure communication channel.

---

CI/scripts/test.sh
src/certifier.mak
src/certifier_tests.mak
src/keystone/shim_test.mak
tests/gen_client_server_certs_key_files.sh

This commit does some clean-up of scripts and Makefiles so that the newly-added test.sh can be used by other dev engineers on diff Linux physical machines.
- Fix few Makefiles to allow re-specifying LOCAL_LIB, to point to, say, /usr/local/lib (for SSL libs, e.g.)
- Hacky support to allow use of OpenSSL V1.x versions
- Add NO_ENABLE_SEV=1 flag in certifier.mak, so that we can build
shared library without #include'ing SEV_SNP-specific code. This
seems to cause pytests which to "hang" as they end up calling
SEV_SNP code-paths.
Use this new flag when building shared-libraries in the  test-run_example-simple_app() test-case, in test.sh .
This is used to execute pytests that need Certifier Service.
---
**NOTE**:  It’s not a complete fix, i.e., it does not address all the points Rado brought up. …

(#215) Fix scripts, Makefiles to have test.sh run on other Linux dev boxes.

---

CI/scripts/test.sh
sample_apps/simple_app_python/example_app.py
tests/README.md
tests/pytests/test_client_server_mtls.py

This commit re-works the way private-key data is managed to be able to call Python SSL interfaces that require certificate and private-key data to be read from files. 
In Python `example_app.py`, private-key data that is instantiated in the `cc_trust_manager{}` object by reading it from the policy-store, will be written to named temp files, in anonymous but-named temp dirs. 
The private-key data will exist **very briefly in the tmp-files** while the SSL certificate-related method is invoked to load-certs.
With this change, `example_app.py` also now handles the case when trust-data is re-loaded from the policy-store by a warm-restart operation. 
Existing pytests have been refactored and extended to add a new pair of client/server tests going thru secure-SSL communication exchange, working …

(#214) Persist private-key data to named temp files. Rework warm_restart() execution.

---

README.md
sample_apps/README.md
sample_apps/multidomain_simple_app/instructions.md
sample_apps/simple_app/instructions.md

Also update sample_apps/README.md to include brief description of simple_app_python and multidomain_simple_app. Clean-up instructions.md in multidomain_simple_app/. Fix few other broken hyperlinks in different md-files.

(#219) Fix few broken hyperlinks to internal docs md-files.

---

src/sev-snp/sev_guest.h
src/sev-snp/sev_support.cc

SEV IOCTL fails when rate limiting kicks in. This patch adds the ioctl retries to handle the rate limiting case internally.

Add IOCTL retries to SEV-SNP support

---

.github/workflows/build.yml
CI/scripts/test.sh
sample_apps/multidomain_simple_app/script
sample_apps/run_example.sh
sample_apps/simple_app/script

This commit extends run_example.sh to build-and-test the multidomain_simple_app sample program.
- Cleaned up `multidomain_simple_app/script` to be usable as a
stand-alone script to run through the workflow.
- Refactored / changed driver `run_example.sh` script to
handle the files needed to support multi-domain certification.
Basically the steps in 'script' are re-implemented in the
workflow of this shell script, so that this run script
can be used as the single-driver script for multi-domain
simple-app testing.
- Add `test-run_example-multidomain_simple_app()` to `test.sh` and
invoke a new test-case from CI `build.yml`

(#167) Extend run_example.sh to build-and-test multidomain simple_app workflow.

---

.github/workflows/build.yml
CI/scripts/test.sh
include/cc_useful.h
include/certifier_algorithms.h
sample_apps/common/example_app.cc
sample_apps/run_example.sh
sample_apps/simple_app/example_app.mak
src/cc_helpers.cc
src/certifier.cc
src/certifier_algorithms.cc

This commit lays down the plumbing to parametrize the names of the public-key and symmetric-key algorithms that will be used by the simple_app. Currently, these are hard-coded to 'Enc_method_rsa_2048' and 'Enc_method_aes_256_cbc_hmac_sha256', respectively.
This commit now supports `--public_key_alg` and `--symmetric_key_alg` flags that can be supplied to the `simple_app/example_app.exe` program.
An initial list of `char *Enc_public_key_algorithms[]` and `char *Enc_symmetric_key_algorithms[]` has been created in `src/certifier_algorithms.cc`. The idea is that we can run test-executions choosing pairs of these algorithms to drive the simple_app.
- Support --public_key_alg and --symmetric_key_alg flags which can be supplied [only] to the simple_app/example_app.exe program.
- An initial list …

(#174) Initial support to parametrize public-key and symmetric-key algorithms.

---

.github/workflows/build.yml
CI/scripts/osinfo.sh
CI/scripts/test.sh
sample_apps/run_example.sh
sev-snp-simulator/Makefile

This commit attempts to keep the CI tests runing cleanly. 
Some tests  are failing due to different issues reported under issue #242 and #244. 
Those will need some minor corrections in build-steps.
For now, 5 test-cases from test.sh are commented out with a  Warning message.
- Skip few simulated-SEV related build-and-test cases.
- Skip ISLET-related build-and-test tests due to rustc version incompatibility.
Those will need to be re-enabled when above two issues are resolved, if possible.
(If further investigation shows that we cannot support Ubunutu 22.04, then some changes will need to be made in CI's build.yml to drop-down  to an older Ubuntu rev-level.)

Stabilize CI-build-and-test jobs on Ubuntu Linux 22.04

---

CI/scripts/test.sh
sample_apps/run_example.sh
third_party/islet/setup.sh

This PR addresses build errors in the Islet SDK. (Fixed https://github.com/ccc-certifier-framework/certifier-framework-for-confidential-computing/issues/244)
**Issues and Resolutions:**
1. **Issue:** Compatibility issues due to the upgrade of a third-party library used by the Islet SDK.
**Fixing:** Upgraded to a compatible version and enforced explicit versioning to prevent automatic upgrades of the third-party library. (https://github.com/islet-project/islet/pull/315)
2. **Issue:** Upgrade of the MRENCLAVE value for the simulated version of Islet SDK targeting x86_64.
**Fixing:** Updated to the upgraded value and added comments on how to obtain it. Although a shell script should ideally be written to fetch the actual value systematically, frequent changes are not anticipated, so only a …

Fix to use the latest Islet SDK 

---

.github/workflows/build.yml
CI/scripts/cppcheck.sh
src/keystone/keystone_tests/keystone_shim.cc
utilities/appoint_platform.cc

Added cppcheck for static analysis. Skipping third_party code for now to avoid some external errors. Also, currently, the check level is normal. We'll increse coverage in the future.

Add cppcheck static analysis

---

Doc/install-certifier-Ubuntu-20.04.md

This PR fixes critical issues #252  in the Ubuntu 20.04 installation documentation that were causing build failures for new users following the official installation guide.
1. **Missing UUID dependency**: Added `uuid-dev` package which is required for compilation but was missing from the original documentation
2. **Deprecated Go commands**: Updated deprecated `go get` commands to modern `go install` commands  
3. **Improved documentation structure**: Added troubleshooting section and better formatting
- Users following the documentation encountered `fatal error: uuid/uuid.h: No such file or directory` during compilation
- The `go get` commands mentioned in the docs are deprecated and caused installation issues
- Multiple users reported these issues, confirmed by maintainer discussion
- …

Fix Ubuntu 20.04 installation docs: add missing UUID dependency and update deprecated Go commands 
